name: basics_samples
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed: ^2.1.0+1
  quiver: ^3.1.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed_annotation: ^2.1.0
