name: flutter_basics_samples
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  bloc: ^9.0.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3

# dependency_overrides:
  # win32: ^5.0.9  # Force une version plus récente de win32

flutter:
  uses-material-design: true
