name: dart_application_1
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  fast_immutable_collections: ^7.4.1

dev_dependencies:
  lints: ^2.0.0