// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 21.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'fighting_zombie_with_flame';

  static const String assets_images_banner_png = 'assets/images/banner.png';
  static const String fighting_zombie_with_flame$assets_images_banner_png = 'packages/fighting_zombie_with_flame/assets/images/banner.png';

  static const String assets_images_barrel_png = 'assets/images/barrel.png';
  static const String fighting_zombie_with_flame$assets_images_barrel_png = 'packages/fighting_zombie_with_flame/assets/images/barrel.png';

  static const String assets_images_character_human_png = 'assets/images/character-human.png';
  static const String fighting_zombie_with_flame$assets_images_character_human_png = 'packages/fighting_zombie_with_flame/assets/images/character-human.png';

  static const String assets_images_character_orc_png = 'assets/images/character-orc.png';
  static const String fighting_zombie_with_flame$assets_images_character_orc_png = 'packages/fighting_zombie_with_flame/assets/images/character-orc.png';

  static const String assets_images_chest_png = 'assets/images/chest.png';
  static const String fighting_zombie_with_flame$assets_images_chest_png = 'packages/fighting_zombie_with_flame/assets/images/chest.png';

  static const String assets_images_coin_png = 'assets/images/coin.png';
  static const String fighting_zombie_with_flame$assets_images_coin_png = 'packages/fighting_zombie_with_flame/assets/images/coin.png';

  static const String assets_images_column_png = 'assets/images/column.png';
  static const String fighting_zombie_with_flame$assets_images_column_png = 'packages/fighting_zombie_with_flame/assets/images/column.png';

  static const String assets_images_dirt_png = 'assets/images/dirt.png';
  static const String fighting_zombie_with_flame$assets_images_dirt_png = 'packages/fighting_zombie_with_flame/assets/images/dirt.png';

  static const String assets_images_door_png = 'assets/images/door.png';
  static const String fighting_zombie_with_flame$assets_images_door_png = 'packages/fighting_zombie_with_flame/assets/images/door.png';

  static const String assets_images_floor_detail_png = 'assets/images/floor-detail.png';
  static const String fighting_zombie_with_flame$assets_images_floor_detail_png = 'packages/fighting_zombie_with_flame/assets/images/floor-detail.png';

  static const String assets_images_floor_png = 'assets/images/floor.png';
  static const String fighting_zombie_with_flame$assets_images_floor_png = 'packages/fighting_zombie_with_flame/assets/images/floor.png';

  static const String assets_images_rocks_png = 'assets/images/rocks.png';
  static const String fighting_zombie_with_flame$assets_images_rocks_png = 'packages/fighting_zombie_with_flame/assets/images/rocks.png';

  static const String assets_images_stairs_png = 'assets/images/stairs.png';
  static const String fighting_zombie_with_flame$assets_images_stairs_png = 'packages/fighting_zombie_with_flame/assets/images/stairs.png';

  static const String assets_images_stones_png = 'assets/images/stones.png';
  static const String fighting_zombie_with_flame$assets_images_stones_png = 'packages/fighting_zombie_with_flame/assets/images/stones.png';

  static const String assets_images_trap_png = 'assets/images/trap.png';
  static const String fighting_zombie_with_flame$assets_images_trap_png = 'packages/fighting_zombie_with_flame/assets/images/trap.png';

  static const String assets_images_wall_half_png = 'assets/images/wall-half.png';
  static const String fighting_zombie_with_flame$assets_images_wall_half_png = 'packages/fighting_zombie_with_flame/assets/images/wall-half.png';

  static const String assets_images_wall_narrow_png = 'assets/images/wall-narrow.png';
  static const String fighting_zombie_with_flame$assets_images_wall_narrow_png = 'packages/fighting_zombie_with_flame/assets/images/wall-narrow.png';

  static const String assets_images_wall_opening_png = 'assets/images/wall-opening.png';
  static const String fighting_zombie_with_flame$assets_images_wall_opening_png = 'packages/fighting_zombie_with_flame/assets/images/wall-opening.png';

  static const String assets_images_wall_png = 'assets/images/wall.png';
  static const String fighting_zombie_with_flame$assets_images_wall_png = 'packages/fighting_zombie_with_flame/assets/images/wall.png';

  static const String assets_images_wood_structure_png = 'assets/images/wood-structure.png';
  static const String fighting_zombie_with_flame$assets_images_wood_structure_png = 'packages/fighting_zombie_with_flame/assets/images/wood-structure.png';

  static const String assets_images_wood_support_png = 'assets/images/wood-support.png';
  static const String fighting_zombie_with_flame$assets_images_wood_support_png = 'packages/fighting_zombie_with_flame/assets/images/wood-support.png';
}
