// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BmIwXOHJrN40kVmaqkTqp6OmJ8hZYNc',
    appId: '1:1023268044020:android:f6958fd88465bf77d9f2a1',
    messagingSenderId: '1023268044020',
    projectId: 'fbs-cloud-messaging-sample',
    storageBucket: 'fbs-cloud-messaging-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe9HimLGjMnIxvFyfjOxvt7xmMIr9tFXk',
    appId: '1:1023268044020:ios:e358d5d04c1f94d9d9f2a1',
    messagingSenderId: '1023268044020',
    projectId: 'fbs-cloud-messaging-sample',
    storageBucket: 'fbs-cloud-messaging-sample.appspot.com',
    iosClientId: '1023268044020-7t7lepaq9ra9kd78vius9ialn8t28tt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicsSamples',
  );
}
